packages:
  - packages/*
  # Temporarily exclude demos and docs for build/publish
  # - demos/*
  # - docs/*

onlyBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - core-js
  - core-js-pure
  - ejs
  - esbuild
  - fsevents
  - protobufjs
  - sharp
  - styled-components
  - svelte-preprocess
  - utf-8-validate
  - vue-demi
  - yorkie

# overrides:
#   '@code-inspector/core': link:packages/core
